### ISSUE TITLE
'PQueueMod' only refers to a type, but is being used as a namespace here.

### ISSUE THREAD

**Issue by ashburnham** [hwchase17/langchainjs#674]
I cannot build on my Mac M1 machine using node v17.9.1 and 8.11.0 due to this error. I've just submitted a PR to fix it..

https://github.com/hwchase17/langchainjs/pull/673

node_modules/langchain/dist/util/async_caller.d.ts:30:22 - error TS2702: 'PQueueMod' only refers to a type, but is being used as a namespace here.

30     protected queue: PQueueMod.default;

**Comment by brunogarcia** [comment]
@ashburnham LangChainJS only works with `"node": ">=18"`.

Check out the `package.json`:

https://github.com/hwchase17/langchainjs/blob/main/package.json#L5

**Comment by nfcampos** [comment]
Resolved in #673 thanks @ashburnham for reporting
