### ISSUE TITLE
LLM run errored with error: t is not a function

### ISSUE THREAD

**Issue by Kartik4152** [hwchase17/langchainjs#1268]
Was trying out the new MultiPromptChain when I encountered the error below.
Tried debugging but couldn't progress much.

Trying this example - https://js.langchain.com/docs/modules/chains/other_chains/multi_prompt_chain

Runtime: Deno - Supabase edge function
Supabase Version - 1.49.4 (as recommended [here](https://github.com/langchain-ai/langchain-template-supabase/)
Lib CDN: https://esm.sh/langchain@0.0.75

It works on Node (using the v0.0.75 package from npm) buts fails on Deno.

![image](https://github.com/hwchase17/langchainjs/assets/22049616/ee755b88-350f-4a73-8592-17ce03ae977b)

**Comment by aseem2625** [comment]
This axios issue is happening somewhere after v0.67 langchainjs version

**Comment by aseem2625** [comment]
@nfcampos Can you please have a look?

This axios issue is happening after v0.67 langchainjs release. This is breaking a few packages, blocker to use those packages with supabase.
