### PR TITLE
Fix env detection for Deno in Supabase Edge Functions

### LINKED ISSUE #1268: LLM run errored with error: t is not a function
Was trying out the new MultiPromptChain when I encountered the error below.
Tried debugging but couldn't progress much.

Trying this example - https://js.langchain.com/docs/modules/chains/other_chains/multi_prompt_chain

Runtime: Deno - Supabase edge function
Supabase Version - 1.49.4 (as recommended [here](https://github.com/langchain-ai/langchain-template-supabase/)
Lib CDN: https://esm.sh/langchain@0.0.75

It works on Node (using the v0.0.75 package from npm) buts fails on Deno.

image

### PR DESCRIPTION
**Pull request by dqbd**
Closes #1268

It does seem like Supabase Deno Functions only provides a global Deno functions _without_ `versions` property, which will mark `isDeno` as `false` and because of NodeJS compat, will mark `isNode` as `true`.

This PR aims to correct both of the properties, which is required to force the `axios-fetch-adapter` in these environments.

### CODE REVIEW

**Review by nfcampos — APPROVED** [review]
Looks great!

File: langchain/src/util/env.ts [hunk 1]
```diff
@@ -1,22 +1,50 @@
...
+  (typeof navigator !== "undefined" &&
+    (navigator.userAgent.includes("Node.js") ||
+      navigator.userAgent.includes("jsdom")));
+
+// Supabase Edge Function provides a `Deno` global object
+// without `version` property
+export const isDeno = () => typeof Deno !== "undefined";
+
+// Mark not-as-node if in Supabase Edge Function
+export const isNode = () =>
```
Comment (dqbd) [inline langchain/src/util/env.ts:31]: Have tried using `/* #__PURE__*/`, but without much luck

**Review by nfcampos — APPROVED** [review]
Great
